### ISSUE TITLE
code after error! fails to compile

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#61] opened 2020-08-28 16:57 UTC
If I try to compile this
![image](https://user-images.githubusercontent.com/16068886/91593278-8e361100-e968-11ea-9bdf-aaf67a08631a.png),
I get such error
![image](https://user-images.githubusercontent.com/16068886/91593294-942bf200-e968-11ea-95b0-b15cecd54d7f.png)

**Comment by jemc** [comment] 2020-08-28 17:14
Suggested solution:

At the end of the `gen_raise_error` function, add the following line:
```crystal
@builder.position_at_end(gen_block("unreachable_after_error"))
```

**Comment by jemc** [comment] 2021-07-06 23:11
The sample code in the OP no longer reproduces the issue because after resolving #75 the compiler rightly rejects the code that tries to print `local_var` when it is not guaranteed to be assigned yet.

Here's a new way to reproduce the bug:
```mare
    try (
      error!
      env.out.print("Hello")
    )
```

**Comment by jemc** [comment] 2021-07-06 23:26
The above solution I suggested is not sufficient. Marking this as complexity: significant instead of simple.

**Closed** 2021-07-07 02:16 UTC
Labels: complexity 2: significant, kind: hole: valid code
